# revision 31584
# category Package
# catalog-ctan /info/examples/LaTeX-Referenz
# catalog-date 2013-09-06 18:52:10 +0200
# catalog-license lppl
# catalog-version undef
Name:		texlive-latex-referenz
Version:	20130906
Release:	3
Summary:	Examples from the book "LaTeX Referenz"
Group:		Publishing
URL:		http://www.ctan.org/tex-archive/info/examples/LaTeX-Referenz
License:	LPPL
Source0:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/latex-referenz.tar.xz
Source1:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/latex-referenz.doc.tar.xz
BuildArch:	noarch
BuildRequires:	texlive-tlpkg
Requires(pre):	texlive-tlpkg

%description
This bundle contains all the examples, as source, eps and pdf,
of the author's book "LaTeX Referenz" (2nd ed.), published by
DANTE/Lehmanns. The examples can be run as usual with the
example class ttctexa.cls, which is in the distribution.

#-----------------------------------------------------------------------
%files
%doc %{_texmfdistdir}/doc/latex/latex-referenz/01-03-1.xltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/01-04-1.lux
%doc %{_texmfdistdir}/doc/latex/latex-referenz/01-04-2.lux
%doc %{_texmfdistdir}/doc/latex/latex-referenz/01-08-1.sh
%doc %{_texmfdistdir}/doc/latex/latex-referenz/01-08-2.sh
%doc %{_texmfdistdir}/doc/latex/latex-referenz/02-03-1.ltx2crop
%doc %{_texmfdistdir}/doc/latex/latex-referenz/02-03-2.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/02-03-3.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/02-03-4.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/03-01-1.lux
%doc %{_texmfdistdir}/doc/latex/latex-referenz/03-03-1.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/03-04-1.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/03-05-1.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/03-06-1.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/03-07-1.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/03-07-2.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/03-08-1.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/03-08-2.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/03-08-3.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/03-08-4.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/03-08-5.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/03-08-6.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/04-02-1.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/05-01-1.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/05-02-1.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-02-1.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-02-10.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-02-11.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-02-12.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-02-13.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-02-14.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-02-15.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-02-16.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-02-17.lux
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-02-18.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-02-2.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-02-3.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-02-4.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-02-5.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-02-6.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-02-7.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-02-8.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-02-9.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-03-1.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-03-10.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-03-11.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-03-12.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-03-13.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-03-14.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-03-15.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-03-16.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-03-17.lux
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-03-18.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-03-2.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-03-3.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-03-4.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-03-5.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-03-6.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-03-7.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-03-8.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-03-9.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-04-1.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-04-10.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-04-11.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-04-12.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-04-13.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-04-14.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-04-15.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-04-16.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-04-17.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-04-18.lux
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-04-19.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-04-2.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-04-20.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-04-21.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-04-22.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-04-23.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-04-3.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-04-4.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-04-5.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-04-6.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-04-7.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-04-8.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-04-9.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-05-1.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-05-10.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-05-11.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-05-12.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-05-13.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-05-14.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-05-15.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-05-16.lux
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-05-17.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-05-18.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-05-19.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-05-2.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-05-20.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-05-21.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-05-22.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-05-23.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-05-3.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-05-4.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-05-5.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-05-6.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-05-7.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-05-8.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-05-9.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/06-06-1.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/07-03-1.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/07-03-10.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/07-03-11.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/07-03-12.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/07-03-13.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/07-03-14.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/07-03-15.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/07-03-16.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/07-03-17.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/07-03-18.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/07-03-19.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/07-03-2.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/07-03-20.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/07-03-21.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/07-03-3.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/07-03-4.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/07-03-5.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/07-03-6.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/07-03-7.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/07-03-8.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/07-03-9.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/07-04-1.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/07-04-2.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/07-04-3.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/07-04-4.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/08-08-1.xltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/08-08-2.xltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/08-08-3.lux
%doc %{_texmfdistdir}/doc/latex/latex-referenz/08-08-4.lux
%doc %{_texmfdistdir}/doc/latex/latex-referenz/08-08-5.lux
%doc %{_texmfdistdir}/doc/latex/latex-referenz/08-08-6.lux
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-03-1.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-03-2.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-03-3.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-03-4.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-05-1.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-05-2.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-05-3.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-05-4.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-05-5.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-05-6.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-05-7.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-05-8.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-07-1.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-07-10.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-07-11.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-07-12.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-07-13.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-07-2.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-07-3.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-07-4.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-07-5.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-07-6.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-07-7.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-07-8.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-07-9.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-08-1.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-08-10.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-08-11.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-08-12.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-08-13.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-08-2.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-08-3.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-08-4.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-08-5.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-08-6.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-08-7.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-08-8.ltxps
%doc %{_texmfdistdir}/doc/latex/latex-referenz/09-08-9.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-02-1.ltx2crop
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-1.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-10.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-11.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-12.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-13.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-14.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-15.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-16.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-17.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-18.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-19.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-2.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-20.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-21.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-22.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-23.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-24.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-25.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-26.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-27.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-28.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-29.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-3.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-30.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-31.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-32.ltx2
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-4.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-5.lux
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-6.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-7.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-8.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/10-03-9.ltx
%doc %{_texmfdistdir}/doc/latex/latex-referenz/DEexa.sty
%doc %{_texmfdistdir}/doc/latex/latex-referenz/DEoptions.sty
%doc %{_texmfdistdir}/doc/latex/latex-referenz/README
%doc %{_texmfdistdir}/doc/latex/latex-referenz/UTF8.bib
%doc %{_texmfdistdir}/doc/latex/latex-referenz/bspfont.cls
%doc %{_texmfdistdir}/doc/latex/latex-referenz/caspervector.bib
%doc %{_texmfdistdir}/doc/latex/latex-referenz/de-examples-dw.bib
%doc %{_texmfdistdir}/doc/latex/latex-referenz/demo11.bib
%doc %{_texmfdistdir}/doc/latex/latex-referenz/exa-fontconfig.tex
%doc %{_texmfdistdir}/doc/latex/latex-referenz/exaarticle.cls
%doc %{_texmfdistdir}/doc/latex/latex-referenz/exaarticle2.cls
%doc %{_texmfdistdir}/doc/latex/latex-referenz/exabook.cls
%doc %{_texmfdistdir}/doc/latex/latex-referenz/exabook2.cls
%doc %{_texmfdistdir}/doc/latex/latex-referenz/examinimal.cls
%doc %{_texmfdistdir}/doc/latex/latex-referenz/examples-dw.bib
%doc %{_texmfdistdir}/doc/latex/latex-referenz/examples.bib
%doc %{_texmfdistdir}/doc/latex/latex-referenz/examplesA.bib
%doc %{_texmfdistdir}/doc/latex/latex-referenz/examplesB.bib
%doc %{_texmfdistdir}/doc/latex/latex-referenz/exareport.cls
%doc %{_texmfdistdir}/doc/latex/latex-referenz/exaxetex.cls
%doc %{_texmfdistdir}/doc/latex/latex-referenz/fontDemo-E.tex
%doc %{_texmfdistdir}/doc/latex/latex-referenz/fontDemo.tex
%doc %{_texmfdistdir}/doc/latex/latex-referenz/hv.bib
%doc %{_texmfdistdir}/doc/latex/latex-referenz/images/B.eps
%doc %{_texmfdistdir}/doc/latex/latex-referenz/images/B.pdf
%doc %{_texmfdistdir}/doc/latex/latex-referenz/klassiker.bib
%doc %{_texmfdistdir}/doc/latex/latex-referenz/l3keysdemo.sty
%doc %{_texmfdistdir}/doc/latex/latex-referenz/luabibentry.lua
%doc %{_texmfdistdir}/doc/latex/latex-referenz/plainDemo.bst
%doc %{_texmfdistdir}/doc/latex/latex-referenz/screxa.cls
%doc %{_texmfdistdir}/doc/latex/latex-referenz/screxabook.cls
%doc %{_texmfdistdir}/doc/latex/latex-referenz/screxareport.cls
%doc %{_texmfdistdir}/doc/latex/latex-referenz/textdemo.sty

#-----------------------------------------------------------------------
%prep
%setup -c -a0 -a1

%build

%install
mkdir -p %{buildroot}%{_texmfdistdir}
cp -fpar doc %{buildroot}%{_texmfdistdir}
